/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.orderapi.entities.public_;


import com.cursojunit.orderapi.entities.DefaultCatalog;
import com.cursojunit.orderapi.entities.public_.tables.Event;
import com.cursojunit.orderapi.entities.public_.tables.Order;
import com.cursojunit.orderapi.entities.public_.tables.Paymentmethod;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1466359047;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.EVENT</code>.
     */
    public final Event EVENT = com.cursojunit.orderapi.entities.public_.tables.Event.EVENT;

    /**
     * The table <code>PUBLIC.ORDER</code>.
     */
    public final Order ORDER = com.cursojunit.orderapi.entities.public_.tables.Order.ORDER;

    /**
     * The table <code>PUBLIC.PAYMENTMETHOD</code>.
     */
    public final Paymentmethod PAYMENTMETHOD = com.cursojunit.orderapi.entities.public_.tables.Paymentmethod.PAYMENTMETHOD;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.SYSTEM_SEQUENCE_7B2B11BC_3786_4E47_B907_5605264F65F8,
            Sequences.SYSTEM_SEQUENCE_7DC84B86_7D62_4E8F_BE97_AA7719BFC85A,
            Sequences.SYSTEM_SEQUENCE_9E694BC4_5B3E_4889_9292_B4DEF286D8F8);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Event.EVENT,
            Order.ORDER,
            Paymentmethod.PAYMENTMETHOD);
    }
}
