/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.orderapi.entities.public_;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_7B2B11BC_3786_4E47_B907_5605264F65F8</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_7B2B11BC_3786_4E47_B907_5605264F65F8 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_7B2B11BC_3786_4E47_B907_5605264F65F8", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_7DC84B86_7D62_4E8F_BE97_AA7719BFC85A</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_7DC84B86_7D62_4E8F_BE97_AA7719BFC85A = new SequenceImpl<Long>("SYSTEM_SEQUENCE_7DC84B86_7D62_4E8F_BE97_AA7719BFC85A", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_9E694BC4_5B3E_4889_9292_B4DEF286D8F8</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_9E694BC4_5B3E_4889_9292_B4DEF286D8F8 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_9E694BC4_5B3E_4889_9292_B4DEF286D8F8", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
