/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.orderapi.entities.public_;


import com.cursojunit.orderapi.entities.public_.tables.Event;
import com.cursojunit.orderapi.entities.public_.tables.Order;
import com.cursojunit.orderapi.entities.public_.tables.Paymentmethod;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.EVENT</code>.
     */
    public static final Event EVENT = com.cursojunit.orderapi.entities.public_.tables.Event.EVENT;

    /**
     * The table <code>PUBLIC.ORDER</code>.
     */
    public static final Order ORDER = com.cursojunit.orderapi.entities.public_.tables.Order.ORDER;

    /**
     * The table <code>PUBLIC.PAYMENTMETHOD</code>.
     */
    public static final Paymentmethod PAYMENTMETHOD = com.cursojunit.orderapi.entities.public_.tables.Paymentmethod.PAYMENTMETHOD;
}
