/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.orderapi.entities.public_.tables.records;


import com.cursojunit.orderapi.entities.public_.tables.Event;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventRecord extends TableRecordImpl<EventRecord> implements Record5<Integer, Integer, String, BigDecimal, Timestamp> {

    private static final long serialVersionUID = -2095039560;

    /**
     * Setter for <code>PUBLIC.EVENT.EVENTID</code>.
     */
    public void setEventid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.EVENT.EVENTID</code>.
     */
    public Integer getEventid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.EVENT.ORDERID</code>.
     */
    public void setOrderid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.EVENT.ORDERID</code>.
     */
    public Integer getOrderid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.EVENT.EVENTTYPE</code>.
     */
    public void setEventtype(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.EVENT.EVENTTYPE</code>.
     */
    public String getEventtype() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.EVENT.AMOUNT</code>.
     */
    public void setAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.EVENT.AMOUNT</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>PUBLIC.EVENT.CREATIONDATE</code>.
     */
    public void setCreationdate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.EVENT.CREATIONDATE</code>.
     */
    public Timestamp getCreationdate() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, BigDecimal, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, BigDecimal, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Event.EVENT.EVENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Event.EVENT.ORDERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Event.EVENT.EVENTTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return Event.EVENT.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Event.EVENT.CREATIONDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEventid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOrderid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEventtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreationdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value1(Integer value) {
        setEventid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value2(Integer value) {
        setOrderid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value3(String value) {
        setEventtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value4(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord value5(Timestamp value) {
        setCreationdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventRecord values(Integer value1, Integer value2, String value3, BigDecimal value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventRecord
     */
    public EventRecord() {
        super(Event.EVENT);
    }

    /**
     * Create a detached, initialised EventRecord
     */
    public EventRecord(Integer eventid, Integer orderid, String eventtype, BigDecimal amount, Timestamp creationdate) {
        super(Event.EVENT);

        set(0, eventid);
        set(1, orderid);
        set(2, eventtype);
        set(3, amount);
        set(4, creationdate);
    }
}
