/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.orderapi.entities.public_.tables.records;


import com.cursojunit.orderapi.entities.public_.tables.Order;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderRecord extends TableRecordImpl<OrderRecord> implements Record7<Integer, Integer, BigDecimal, String, Integer, BigDecimal, Timestamp> {

    private static final long serialVersionUID = 1883800837;

    /**
     * Setter for <code>PUBLIC.ORDER.ORDERID</code>.
     */
    public void setOrderid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER.ORDERID</code>.
     */
    public Integer getOrderid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ORDER.CUSTOMERID</code>.
     */
    public void setCustomerid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER.CUSTOMERID</code>.
     */
    public Integer getCustomerid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.ORDER.AMOUNT</code>.
     */
    public void setAmount(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER.AMOUNT</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>PUBLIC.ORDER.SKU</code>.
     */
    public void setSku(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER.SKU</code>.
     */
    public String getSku() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.ORDER.QUANTITY</code>.
     */
    public void setQuantity(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER.QUANTITY</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>PUBLIC.ORDER.VALUE</code>.
     */
    public void setValue(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER.VALUE</code>.
     */
    public BigDecimal getValue() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>PUBLIC.ORDER.CREATIONDATE</code>.
     */
    public void setCreationdate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER.CREATIONDATE</code>.
     */
    public Timestamp getCreationdate() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, BigDecimal, String, Integer, BigDecimal, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, BigDecimal, String, Integer, BigDecimal, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Order.ORDER.ORDERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Order.ORDER.CUSTOMERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return Order.ORDER.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Order.ORDER.SKU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Order.ORDER.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return Order.ORDER.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Order.ORDER.CREATIONDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOrderid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCustomerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreationdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value1(Integer value) {
        setOrderid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value2(Integer value) {
        setCustomerid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value3(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value4(String value) {
        setSku(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value5(Integer value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value6(BigDecimal value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value7(Timestamp value) {
        setCreationdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord values(Integer value1, Integer value2, BigDecimal value3, String value4, Integer value5, BigDecimal value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderRecord
     */
    public OrderRecord() {
        super(Order.ORDER);
    }

    /**
     * Create a detached, initialised OrderRecord
     */
    public OrderRecord(Integer orderid, Integer customerid, BigDecimal amount, String sku, Integer quantity, BigDecimal value, Timestamp creationdate) {
        super(Order.ORDER);

        set(0, orderid);
        set(1, customerid);
        set(2, amount);
        set(3, sku);
        set(4, quantity);
        set(5, value);
        set(6, creationdate);
    }
}
